# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

ENV GOTOOLCHAIN=auto

# Copy go mod files
COPY f1sim/go.mod f1sim/go.sum* ./

# Download dependencies
RUN go mod download

# Copy source code
COPY f1sim/ ./

# Build the simulator application
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/listener ./cmd/listener/main.go

# Final stage
FROM alpine:latest

WORKDIR /root/

# Copy binary from builder
COPY --from=builder /app/listener .

EXPOSE 20777/udp

CMD ["./simulator"]

